/* Creación de la base de datos #1 */
CREATE DATABASE logisticaMdp;
USE logisticaMdp;
GO

/* Validacion de existencia de tablas */
IF OBJECT_ID('CATEGORY','U') IS NOT NULL
DROP TABLE CATEGORY
    IF OBJECT_ID('PRODUCTS','U') IS NOT NULL
DROP TABLE PRODUCTS

/* Creación de las tablas #2 */
CREATE TABLE CATEGORY (
    ID_CATEGORY int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NAME_CATEGORY varchar(255) NOT NULL,
    DATE_CATEGORY varchar(15) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID_PRODUCT int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NAME_PRODUCT varchar(150) NOT NULL,
    CATEGORY int NOT NULL,
    DESCRIPTION_PRODUCT varchar(255),
    STOCK int NOT NULL,
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
);

/* Inserción de Data #3 */
INSERT INTO CATEGORY (NAME_CATEGORY, DATE_CATEGORY)
VALUES
    ('Higiene', '17/04/2023'),
    ('Materiales', '18/04/2023'),
    ('Suministros', '19/04/2023');

INSERT INTO PRODUCTS (NAME_PRODUCT, CATEGORY, DESCRIPTION_PRODUCT, STOCK)
VALUES
    ('PAPEL HIGIENICO', 1, 'PAPEL HIGIENICO', 5),
    ('PASTA DENTAL', 1, 'PASTA DENTAL', 9),
    ('PAPEL BON', 2, 'PAPEL BON', 7),
    ('CRAYONES', 2, 'CRAYONES', 12),
    ('PAPITAS', 3, 'PAPITAS', 7),
    ('ARROZ', 3, 'ARROZ', 12);