/* Creación de la base de datos #1 */
CREATE DATABASE logisticaMdp;
USE logisticaMdp;
GO

/* Validacion de existencia de tablas */
IF OBJECT_ID('PRODUCTS','U') IS NOT NULL
DROP TABLE PRODUCTS
IF OBJECT_ID('CATEGORY','U') IS NOT NULL
DROP TABLE CATEGORY
IF OBJECT_ID('PRODUCT_OUTPUTS','U') IS NOT NULL
DROP TABLE PRODUCT_OUTPUTS

/* Creación de las tablas #2 */
CREATE TABLE CATEGORY (
    ID_CATEGORY int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NAME_CATEGORY varchar(255) NOT NULL,
    DATE_CATEGORY date NOT NULL
);

CREATE TABLE PRODUCTS (
    ID_PRODUCT int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NAME_PRODUCT varchar(150) NOT NULL,
    CATEGORY int NOT NULL,
    DESCRIPTION_PRODUCT varchar(255),
    STOCK int NOT NULL,
	DATE_PRODUCT date NOT NULL, 
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
);

CREATE TABLE PRODUCT_OUTPUTS (
    ID_PRODUCT_OUTPUTS int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PRODUCT int NOT NULL,
    QUANTITY int NOT NULL,
    AREA varchar(100),
    DATE_PRODUCT_OUTPUTS date NOT NULL,
    FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT),
);

/* Inserción de Data #3 */
INSERT INTO CATEGORY (NAME_CATEGORY, DATE_CATEGORY)
VALUES
    ('Higiene', CONVERT (date, GETDATE())),
    ('Materiales', CONVERT (date, GETDATE())),
    ('Suministros', CONVERT (date, GETDATE()));

INSERT INTO PRODUCTS (NAME_PRODUCT, CATEGORY, DESCRIPTION_PRODUCT, STOCK, DATE_PRODUCT)
VALUES
    ('PAPEL HIGIENICO', 1, 'PAPEL HIGIENICO', 5, CONVERT (date, GETDATE())),
    ('PASTA DENTAL', 1, 'PASTA DENTAL', 9, CONVERT (date, GETDATE())),
    ('PAPEL BON', 2, 'PAPEL BON', 7, CONVERT (date, GETDATE())),
    ('CRAYONES', 2, 'CRAYONES', 12, CONVERT (date, GETDATE())),
    ('PAPITAS', 3, 'PAPITAS', 7, CONVERT (date, GETDATE())),
    ('ARROZ', 3, 'ARROZ', 12, CONVERT (date, GETDATE()));

INSERT INTO PRODUCT_OUTPUTS (PRODUCT, QUANTITY, AREA, DATE_PRODUCT_OUTPUTS)
VALUES
    (1, 1, 'AREA INDUSTRIAL', CONVERT (date, GETDATE())),
    (2, 1, 'AREA INDUSTRIAL', CONVERT (date, GETDATE())),
    (3, 2, 'AREA INDUSTRIAL', CONVERT (date, GETDATE())),
    (4, 2, 'AREA INDUSTRIAL', CONVERT (date, GETDATE())),
    (5, 3, 'AREA INDUSTRIAL', CONVERT (date, GETDATE())),
    (6, 3, 'AREA INDUSTRIAL', CONVERT (date, GETDATE()));
